apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: kanna
spec:
  args:
  - name: service-name
  metrics:
  - name: pod-availability
    # 기본적인 Pod 가용성 체크 (Pod가 Ready 상태인지)
    successCondition: result[0] >= 1
    interval: 10s
    count: 1
    provider:
      prometheus:
        address: https://mon.montkim.com/prometheus
        query: |
          sum(
            kube_pod_status_ready{
              namespace="kanna",
              pod=~"kanna-.*",
              condition="true"
            }
          ) 