apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: kanna
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    # 기본적인 성공률 체크 (HTTP 200 응답률)
    successCondition: result[0] >= 0.95
    interval: 60s
    count: 5
    provider:
      prometheus:
        address: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        query: |
          sum(irate(
            nginx_ingress_controller_requests{
              ingress="kanna-ingress",
              status!~"[4-5].*"
            }[2m]
          )) / 
          sum(irate(
            nginx_ingress_controller_requests{
              ingress="kanna-ingress"
            }[2m]
          )) 