apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanna
  namespace: kanna
spec:
  replicas: 3
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: kanna
  template:
    metadata:
      labels:
        app: kanna
    spec:
      containers:
      - name: kanna
        image: art.montkim.com/public/kanna:71c423
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
      nodeSelector:
        montapp: enabled