apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanna
  namespace: kanna
spec:
  replicas: 3
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  selector:
    matchLabels:
      app: kanna
  template:
    metadata:
      labels:
        app: kanna
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100  # 높은 우선순위
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - kanna
              topologyKey: "kubernetes.io/hostname"  # 동일 노드에서 스케줄링되지 않도록 설정
      containers:
      - name: kanna
        image: art.montkim.com/public/kanna:925558
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        startupProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10  # 컨테이너가 시작된 후 10초 대기
          periodSeconds: 10         # 요청 주기
          timeoutSeconds: 2        # 요청 제한 시간
          failureThreshold: 10     # 실패 허용 임계치 (최대 10회 실패 허용)
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 2
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 2
          failureThreshold: 3
      nodeSelector:
        montapp: enabled