apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kanna-app
  namespace: kanna

# 모든 매니페스트 파일 포함
resources:
  - rollout.yaml
  - services-rollout.yaml
  - analysis-template.yaml
  - svc.yaml  # 기존 서비스 (필요시 제거 가능)
  - ingress.yaml

# 이미지 태그 관리 (ArgoCD Image Updater 사용시)
images:
  - name: idoyo7/kanna
    newTag: 8ff103

# 공통 라벨 추가
commonLabels:
  app.kubernetes.io/name: kanna
  app.kubernetes.io/part-of: kanna-app
  app.kubernetes.io/managed-by: argocd

# 공통 어노테이션 추가
commonAnnotations:
  argocd.argoproj.io/sync-wave: "1" 