apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: kanna
  namespace: kanna
spec:
  replicas: 3
  revisionHistoryLimit: 5
  strategy:
    blueGreen:
      # Blue-Green 배포 전략 설정
      activeService: kanna-service-active
      previewService: kanna-service-preview
      autoPromotionEnabled: false  # 수동 승격
      scaleDownDelaySeconds: 30
      prePromotionAnalysis:
        templates:
        - templateName: success-rate
        args:
        - name: service-name
          value: kanna-service-preview
      postPromotionAnalysis:
        templates:
        - templateName: success-rate
        args:
        - name: service-name
          value: kanna-service-active
  selector:
    matchLabels:
      app: kanna
  template:
    metadata:
      labels:
        app: kanna
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - kanna
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: kanna
        image: idoyo7/kanna:8ff103
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        startupProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 20
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3 